services:
  - type: web
    name: apparels-backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/apparels-management-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DDL_AUTO
        value: update
